name: Build & serve site
on:
  push:
    branches:
      - master 
      - main
  workflow_dispatch:
    
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prep Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install pip deps
        run: |
          python -m pip install --user mkdocs-material mkdocstrings[python]
      - name: Build and deploy site
        run: mkdocs gh-deploy --force